name: block_xaero_web
description: Block-Xaero Projects Showcase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.6
  # Removed Google Fonts due to compatibility issues
  flutter_svg: ^1.1.5
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  fonts:
  - family: FiraCode
    fonts:
    - asset: assets/fonts/FiraCode-Regular.ttf
    - asset: assets/fonts/FiraCode-Bold.ttf
      weight: 700
  - family: SourceCodePro
    fonts:
    - asset: assets/fonts/SourceCodePro[wght].ttf
    - asset: assets/fonts/SourceCodePro[wght].ttf
      weight: 700
