name: Deploy to GitHub Pages

on:
  push:
    branches: [ main , gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.5'
        channel: 'stable'
    - name: Add Dart SDK to PATH
      run: echo "$FLUTTER_ROOT/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: flutter pub get
    - name: Build web
      run: flutter build web --release --base-href=/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./build/web
        publish_branch: gh-pages
