name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Updated to v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.18.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web --release --base-href=/  # Added base-href

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web